language: node_js
addons:
  ssh_known_hosts: github.com
before_install:
 - openssl aes-256-cbc -K $encrypted_01897fd6d767_key -iv $encrypted_01897fd6d767_iv
   -in deploy_rsa.enc -out deploy_rsa -d
install:
 - npm install -g gitbook-cli
script:
 - echo "Importing SSH Key"
 - eval "$(ssh-agent -s)"
 - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
 - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
 - echo "Configuring Git"
 - git config --global user.email "we.sss.you@gmail.com"
 - git config --global user.name "SSS Wiki Bot (via TravisCI)"
 - echo "Fetching Repo"
 - mkdir _book
 - cd _book
 - git init
 - git remote add origin git@github.com:skhu-sss/skhu-sss.github.io.git
 - git checkout master
 - git pull origin master
 - echo "Building Pages"
 - cd ..
 - gitbook build
 - cd _book
 - echo "Pushing Updates"
 - git add .
 - git commit -m "Updated Contents - via Travis CI"
 - git push origin master
